### ISSUE TITLE
Add new notifications collection

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1042]
- [x] basic layout for notifications #1096 

- [x] scrollable collection, like the quads in portfolio page, except this is one of 6. #1096 

- [x] Each item in collection of notifications with correct messaging depending on type.

- [x] each item will have a `view` button to bring up correct modal.

- [x] Need to show how many notifications are in the collection and how many are new. see mocks #1096 
- [x] Add notification to app state to allow UX around new vs stale cards (showing new/stale status TODO)

Notification Cards to Create
types of notifications: (there is an associated modal, see modal tix)

- [x] unsigned orders #1246
- [x] open orders in resolved market  #1122 
- [x] designated report with count down timer #1121
- [x] dispute round #1160 
- [x] market in awaiting_finalization where user has winning position #1148 
- [x] user has complete sets and can sell them to get ETH #1233 
- [x] cash in winning shares on finalized market #1245
- [x] market maker can claim validity bond (ETH) and no-show bond (REP) from mailbox #1244
- [x] user claim reporting stake and fees #1622/1623

**Comment by bthaile** [comment]
@Chwy5 see the list of notifications at the end of the description, these can be tested.

**Comment by Chwy5** [comment]
unsigned orders #1246 I didnt get this notification...I triggered an orphaned order(here is tx hash for it) 0xfe93c22d73432a4f0425806eb4e67505bf1d62a19e63ac05d132376bd8506d35....didnt get notifiaction in Notifiaction section
open orders in resolved market  #1122 - yes this works
designated report with count down timer #1121 - I didnt get this notification.  I created a market in Acct 1 and made Acct 2 the designated reporter...never got notification in acct 2 or countdown clock
dispute round #1160
market in awaiting_finalization where user has winning position #1148- yes i got this
user has complete sets and can sell them to get ETH #1233- I got this
cash in winning shares on finalized market #1245- I got this
market maker can claim validity bond (ETH) and no-show bond (REP) from mailbox #1244 _ i Have not got this

**Comment by bthaile** [comment]
Moved unsigned orders not working to https://github.com/AugurProject/augur-ui/issues/2786
Moved dr doesn't get timer to https://github.com/AugurProject/augur-ui/issues/2787
Moved market maker doesn't get notification to claim validity bond and no-show bond to https://github.com/AugurProject/augur-ui/issues/2788

**Comment by andrewdamelio** [comment]
@bthaile we good to close this issue? Seems like everything is being tracked in other issues.

**Comment by Chwy5** [comment]
closing...tracked in individual tickets
