### ISSUE TITLE
upgrade trezor-connect npm package

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1581]
### Update Trezor-Connect (for v1 & v2)

trezor-connect is outdated and needs to be updated in order to better support the Trezor One and Trezor Modal T.

#### TODO
- [x] update trezor-connect
- [x] test with Trezor One
- [x] test with Trezor Model T

**Comment by Chwy5** [comment]
Approved

**Comment by andrewdamelio** [comment]
@Chwy5  @bthaile FYI tested this using the newer Trezor (Trezor Model T) and it does not work for this hardware wallet. 

Updating to v7 fixed it on my end (plus some code wrangling) -- This seems like a big issue for Trezor users.

**Comment by andrewdamelio** [comment]
@Chwy5 Someone reported this later that day in ISSUES so it appears to be an issue for all. 

We currently aren't supporting the newest Trezor hardware device.

**Comment by Chwy5** [comment]
approved...needs to be added to the list of updates

**Comment by bthaile** [comment]
We'll need to re-create this change for V2

**Comment by andrewdamelio** [comment]
@pgebheim Question regarding https://github.com/trezor/connect/blob/develop/docs/index.md#trezor-connect-manifest

In terms of the manifest, is there anyone specific from FF I should use for email?
```
TrezorConnect.manifest({
    email: 'developer@xyz.com',
    appUrl: 'http://your.application.com'
})
```

**Comment by pgebheim** [comment]
team@augur.net

**Comment by phoebemirman** [comment]
@Chwy5 is waiting for his trezor to arrive. closing this for now
