### ISSUE TITLE
Desktop Trading Page: Candlesticks Chart

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1602]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/0af455b7-a09f-49be-8b3f-80cf76c2c93d)
Left: Design | Right: Code

- [ ] ~~add 1px rounding to candlestick bodies~~ (moved to https://github.com/AugurProject/augur/issues/1839)
- [x] move volume bars behind candlesticks. Add 2px rounding to the tops of these bars
- [x] Move OCHL to the left. See details below for spacing and positioning
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/5c253ca2-0879-4d36-afe2-91f2a930688e)

Further guidance for spacing elements
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/9892eb85-721b-4ab8-bf0b-3f72187278c7)

- [x] OCHL labels should only show on interaction 

- [ ] ~~update the interaction styling showing exact date and eth - see design. These overlays should line up with the numbers behind them~~ (moved to https://github.com/AugurProject/augur/issues/1839)

- [x] Add ETH label here and remove from labels
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/ed0bcc70-d47c-453e-924f-1723219b0753)

- [x] Y axis labels should be 10px Mono Bold

- [x] X axis labels are 9px Mono Reg

- [ ] ~~Fix spacing around top and bottom of x axis labels~~ (moved to https://github.com/AugurProject/augur/issues/1839)
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/767158b3-05b0-474a-9de0-b2a3ec133361)
left:build | Right: Design

**Comment by bthaile** [comment]
Moved not accomplished items to tix https://github.com/AugurProject/augur/issues/1839

**Comment by matt-bullock** [comment]
Looks good. Creating separate tickets for a couple of issues I've spotted
