### ISSUE TITLE
[Design Epic Template]

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1609]
Problem: 
Description of the problem we're solving with this piece of work. 

- [ ] **Articulate the problem**
    - [ ] Write product doc with product (problems, CUJs, ideas)
       - [ ] Gather any feedback (GH, team, user feedback on Discord, Reddit etc) 
       - [ ] Meeting with any team members who have knowledge on the topic 
    - [ ] Do you have a clear picture of the problem you need to solve? 
- [ ] **Explore different solutions (go wide)**
    - [ ] What are common patterns that solve similar problems? 
    - [ ] Explore 3 x different approaches 
    - [ ] Review with product and dev
    - [ ] Run a user study (optional)  
    - [ ] Decide on a direction 
- [ ] **Design solution (start small)**
    - [ ] Scope the solution, what’s in, what’s out
    - [ ] Design the components, flows, states 
    - [ ] Design all breakpoints 
    - [ ] Review with product and dev 
    - [ ] Run a user study (optional) 
    - [ ] Iterate (cycles of design/review) 
    - [ ] Finalise 
- [ ] **Write it up**
    - [ ] Write GitHub tickets for the UI team
       - [ ] Break the piece of work down into logical groupings for dev
       - [ ] Describe components, flows and states 
    - [ ] Walk-through with dev

**Comment by pgebheim** [comment]
@cillianhunter0 -- Lets put this into Github templates.

Need help with that?

**Comment by cillianhunter0** [comment]
I don't seem to have permissions to add a template. Following this guide:
https://help.github.com/en/articles/creating-issue-templates-for-your-repository

I'm not seeing the settings tab.
