### ISSUE TITLE
Trading: Market cards

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1833]
Market cards currently take up too much space and don't provide enough information to help users identify markets of interest. 

[Product scope doc](https://docs.google.com/document/d/1YqCl3_nMk9rhmdQroG6IUaacw2c5t4GhehCXN1A7XLE/edit?usp=sharing) 

- [ ] **Design solution (start small)**
    - [ ] Review work on cards redesign to date
    - [ ] Scope the solution, what’s in, what’s out
    - [ ] Design the components, flows, states 
    - [ ] Design all breakpoints 
    - [ ] Review with product and dev 
    - [ ] Run a user study (optional) 
    - [ ] Iterate (cycles of design/review) 
    - [ ] Finalise 
- [ ] **Write it up**
    - [ ] Write GitHub tickets for the UI team
       - [ ] Break the piece of work down into logical groupings for dev
       - [ ] Describe behaviour  
    - [ ] Walk-through with dev

**Comment by pgebheim** [comment]
@matt-bullock @cillianhunter0 @Chwy5 

Is this ticket done and are all the sub-components of this actually done?
