### ISSUE TITLE
Categories 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1834]
This piece of work will focus on an iterative improvement to the category list on the Market List page. It will not focus on changing how the current category/tag system works, we will explore this after we redesign the market creation process. 

[Product scope doc](https://docs.google.com/document/d/1mp4jsNwoxJjg_vnGU73Vjz6meAWIWO28RAPCBeYY9rk/edit?usp=sharing)

- [ ] **Design solution (start small)**
    - [x] Scope the solution, what’s in, what’s out
    - [ ] Wireframe solution
    - [ ] Review  
    - [ ] Design the components, flows, states 
    - [ ] Design all breakpoints 
    - [ ] Review with product and dev 
    - [ ] Run a user study (optional) 
    - [ ] Iterate (cycles of design/review) 
    - [ ] Finalise 
- [ ] **Write it up**
    - [ ] Write GitHub tickets for the UI team
       - [ ] Break the piece of work down into logical groupings for dev
       - [ ] Describe behaviour  
    - [ ] Walk-through with dev
