### ISSUE TITLE
Trading: Categories, Search, Filters

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1837]
This will include settings for market list page (e.g. experimental filter, anything that's preset that's used very rarely) 

Note from previous category ticket: 
This piece of work will focus on an iterative improvement to the category list on the Market List page. It will not focus on changing how the current category/tag system works, we will explore this after we redesign the market creation process.

Product scope doc
https://docs.google.com/document/d/1mp4jsNwoxJjg_vnGU73Vjz6meAWIWO28RAPCBeYY9rk/edit

Note on spread filter: 

* Need to add in the spread filter, v2 chwy mentioned he wants to call it the bid/ask spread

- - -
* [ ] **Articulate the problem**
  * [ ] Write product doc with product (problems, CUJs, ideas)
    * [ ] Gather any feedback (GH, team, user feedback on Discord, Reddit etc) 
    * [ ] Meeting with any team members who have knowledge on the topic 
  * [ ] Do you have a clear picture of the problem you need to solve? 
* [ ] **Explore different solutions (go wide)**
  * [ ] What are common patterns that solve similar problems? 
  * [ ] Explore 3 x different approaches 
  * [ ] Review with product and dev
  * [ ] Run a user study (optional)
  * [ ] Decide on a direction 
* [ ] **Design solution (start small)**
  * [ ] Scope the solution, what’s in, what’s out
  * [ ] Design the components, flows, states 
  * [ ] Design all breakpoints 
  * [ ] Review with product and dev 
  * [ ] Run a user study (optional) 
  * [ ] Iterate (cycles of design/review) 
  * [ ] Finalise 
* [ ] **Write it up**
  * [ ] Write GitHub tickets for the UI team
    * [ ] Break the piece of work down into logical groupings for dev
    * [ ] Describe components, flows and states 
  * [ ] Walk-through with dev
