### ISSUE TITLE
Betting: Market list page

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#2018]
Including three primary states: 
- Logged out user
- New user
- Active user

**Comment by yanelbottini** [comment]
# Design done list

## Logged out user

### Desktop
- [ ] Landing Page

### Responsive
- [ ] Mobile breakpoint
- [ ] Tablet breakpoint

## New User

### Desktop
- [ ] Landing Page with on boarding message
- [ ] On boarding card

### Responsive
- [ ] Mobile breakpoint
- [ ] Tablet breakpoint

## Active User

### Desktop
- [ ] Landing Page with stats
- [ ] Market list while exploring Main Category
- [ ] Market list while exploring Subcategory
- [ ] Market list with filters applied
- [ ] Search results
- [ ] Search results: No results

### Responsive
- [ ] Mobile breakpoint
- [ ] Tablet breakpoint
