### ISSUE TITLE
Betting: Market page

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#2019]
# Design done list

### Desktop
- [ ] Categorical Market: Open Status
- [ ] Categorical Market: In Reporting Status
- [ ] Categorical Market: Finalized Status
- [ ] Categorical Market: Finalized Status, Winning bets
- [ ] Scalar Market: Open Status
- [ ] Scalar Market: In Reporting Status
- [ ] Scalar Market: Finalized Status
- [ ] Scalar Market: Finalized Status, Winning bets

### Mobile
- [ ] Categorical Market: Open Status
- [ ] Categorical Market: In Reporting Status
- [ ] Categorical Market: Finalized Status
- [ ] Categorical Market: Finalized Status, Winning bets
- [ ] Scalar Market: Open Status
- [ ] Scalar Market: In Reporting Status
- [ ] Scalar Market: Finalized Status
- [ ] Scalar Market: Finalized Status, Winning bets

### Tablet
- [ ] Categorical Market: Open Status
- [ ] Scalar Market: Open Status
