### ISSUE TITLE
Betting: App bar refinements

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#2021]
Review and make sure in sync with trading:

* Navigation, wallet, settings etc

**Comment by yanelbottini** [comment]
# Design done list

### Desktop
- [ ] Logged out user
- [ ] Logged in user
- [ ] Wallet information
- [ ] Transaction notifications information
- [ ] Settings information

### Responsive
- [ ] Mobile breakpoint
- [ ] Tablet breakpoint
