### ISSUE TITLE
Trading: Market creation

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#2032]
Redesign of the market creation process. 

- [x] **Articulate the problem**
    - [x] Write product doc with product (problems, CUJs, ideas)
       - [x] Gather any feedback (GH, team, user feedback on Discord, Reddit etc) 
       - [x] Speak with any team members who have knowledge on the topic 
    - [x] Do you have a clear picture of the problem you need to solve? 
- [x] **Explore different solutions (go wide)**
    - [x] What are common patterns that solve similar problems? 
    - [x] Explore 3 x different approaches 
    - [x] Review with product and dev
    - [x] Run a user study (optional)  
    - [x] Decide on a direction 
- [ ] **Design solution (start small)**
    - [x] Scope the solution, what’s in, what’s out
    - [ ] Design the components, flows, states (see comment below for design done)
    - [x] Design all breakpoints 
    - [x] Review with product and dev 
    - [x] Run a user study (optional) 
    - [ ] Iterate (cycles of design/review) 
    - [ ] Finalise 
- [ ] **Write it up**
    - [ ] Write GitHub tickets for the UI team
       - [ ] Break the piece of work down into logical groupings for dev
       - [ ] Describe behaviour  
    - [ ] Walk-through with dev

**Comment by cillianhunter0** [comment]
# Design done list  

## Pages 

#### Desktop
- [x] Market creation home
   - [x] Create from template
   - [x] Create custom
   - [x] Import template
   - [x] Saved drafts
- [x] Template flow
   - [x] Sub-category
   - [x] Market type
   - [x] Template
   - [x] Event details (yes/no)
   - [x] Event details (multiple choice)
   - [x] Event details (scalar)
- [x] Custom form
   - [x] Yes/no
   - [x] Multiple choice
   - [x] Scalar
- [x] Fee and liquidity 
   - [x] Market creator fee
   - [ ] Odds calculator 
   - [ ] Empty states
   - [ ] Spread filter alerts 
- [x] Review
   - [x] Preview market
   - [ ] Flow after user taps “Create market” button

#### Mobile
- [x] Market creation home
   - [x] Create from template
   - [x] Create custom
   - [x] Import template
   - [x] Saved drafts
- [x] Template flow
   - [x] Sub-category
   - [x] Market type
   - [x] Template
   - [x] Event details (yes/no)
   - [x] Event details (multiple choice)
   - [x] Event details (scalar)
- [x] Custom form
   - [x] Yes/no
   - [ ] Multiple choice
   - [ ] Scalar
- [ ] Fee and liquidity 
   - [ ] Market creator fee
   - [ ] Odds calculator 
   - [ ] Empty states
   - [ ] Spread filter alerts 
- [x] Review
   - [x] Preview market
   - [ ] Flow after user taps “Create market” button

#### Responsive
- [x] Market creation home
- [x] Form
- [ ] Fee and liquidity 
- [x] Review

## Components 

#### Radio buttons
- [x] Design all states 
- [x] Componentized

#### Radio buttons - 2 lines
- [x] Design all states 
- [x] Componentized

#### Radio button (card)
- [x] Design all states 
- [x] Componentized

#### Modals
- [x] Design "learn more" modal component 
- [x] Design "select category" modal component 
- [ ] Componentized

#### Text input
- [x] Design all states 
- [x] Componentized

#### Dropdown
- [x] Design all states 
- [x] Componentized

#### Date picker 
- [ ] Design all states 
- [x] Componentized
- [ ] Mobile version

#### Time picker 
- [ ] Design all states 
- [x] Componentized
- [ ] Mobile version

#### Timezone picker 
- [x] Design all states 
- [x] Componentized

#### Breadcrumbs
- [x] Design all states 
- [x] Componentized
- [ ] Mobile version

## Behaviour to spec 

#### Templated flow
- [ ] Sub-category: Detail the behaviour of choosing a different sub-cat
- [ ] Categorical: Detail the behaviour between market question and outcomes 
- [ ] Scalar: Detail the behaviour between market question and the scalar inputs 

#### Liquidity page
- [ ] Detail the behaviour of spread filter alerts

#### Review page
- [ ] Detail the behaviour of previewing the market
- [ ] Detail the behaviour of post-create flow 

## Content list
Full list needs to be compiled. 

#### Market templates
- [ ] 
- [ ] 

#### Tooltips
- [ ] 
- [ ] 

#### Learn more modals
- [ ] 
- [ ]
