### ISSUE TITLE
Trading: Market comments

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#2373]
Market comments

* Disqus like thread below the trading UI

Notes

* Site chat that refreshes every 24 hours
* Market chat that's more like comment section 
* RFQ feature allows users to post an RFQ to chat - refreshes every 24 hours
  * Creators side 
    * Minimum RFQ requirement size (100k) 
    * Minimum trade size (10% = 10k)

    * Choose market 
  * Takers side 
    * Need a order ticket form to make an offer
      * Minimum size (10% etc)
      * Individual price 
  * Interactions
    * Need to be able to respond to offers 
      * No - with comment
      * Yes - triggers fill flow 
  * When both parties accept it triggers the order to fill 

**Problem:**
Description of the problem we're solving with this piece of work. 

* [ ] **Articulate the problem**
  * [ ] Write product doc with product (problems, CUJs, ideas)
    * [ ] Gather any feedback (GH, team, user feedback on Discord, Reddit etc) 
    * [ ] Meeting with any team members who have knowledge on the topic 
  * [ ] Do you have a clear picture of the problem you need to solve? 
* [ ] **Explore different solutions (go wide)**
  * [ ] What are common patterns that solve similar problems? 
  * [ ] Explore 3 x different approaches 
  * [ ] Review with product and dev
  * [ ] Run a user study (optional)
  * [ ] Decide on a direction 
* [ ] **Design solution (start small)**
  * [ ] Scope the solution, what’s in, what’s out
  * [ ] Design the components, flows, states 
  * [ ] Design all breakpoints 
  * [ ] Review with product and dev 
  * [ ] Run a user study (optional) 
  * [ ] Iterate (cycles of design/review) 
  * [ ] Finalise 
* [ ] **Write it up**
  * [ ] Write GitHub tickets for the UI team
    * [ ] Break the piece of work down into logical groupings for dev
    * [ ] Describe components, flows and states 
  * [ ] Walk-through with dev
