### ISSUE TITLE
condensed: market trading page checklist

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3650]
General ticket to get market trading page parity with design. includes all responsiveness changes

 - [x] header (reporting/disputing/claim button area)
 - [x] order book
 - [x] trading history
 - [ ] charts
 - [x] outcome list
 - [x] user section (open orders, filled orders, positions)
- [x] order form
- [x] add condensing arrows
- [x] overall layout changes

Design is ready, it's still moving around/ cleanup / organizing components.
<https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=453%3A59625>

![image](https://user-images.githubusercontent.com/3970376/65272506-d60bb180-dae4-11e9-8ca0-b5301af2bb1c.png)
