### ISSUE TITLE
Onboarding: desktop issues/tweaks

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#4236]
- [x] Copy in step 3 modal: 
Update to "See how betting works on Augur. You’ll get guidance and tips to help you get started."

- [x] Signup/login modal: 
Align this text on same line
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/4184453c-e55a-4749-9a4b-9d9ff7052853)

- [x] Hover state color of blue signup with email button is too bright, let's use 00A1B0 which is 5% increase in brightness.

- [x] Connect wallet modal: 
Sub-head text = 14px, line height should be increased (design on left, build on right) 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/d73dae7e-febf-4c9f-8da6-33ba603d40ea)

- [x] Signup with portis:  
- permission modal, can we add in a message here to explain why?  [see #4181]

- [x] Add funds modal:
- Asset to buy button styling, height/weight is a little large and stroke should be 1px (build on left, design on right) 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/ac7c7a15-4edf-4364-a873-5bfcff427d18)

- [x] Add funds modal: 
- Right side sub-heading, can reduce padding between it and heading. The tooltip color should be text-secondary color and lowered slightly to bring in line. (build on top, design on bottom)
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/bf7e4a89-5552-445b-b57f-30703c34942d)

- [x] Add funds modal: 
need help text in left panel. Tooltip colour should be text-secondary. Tooltip alignment is correct. Reduce padding between learn how copy and learn more link by 2px. 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/33062622-26f4-4b40-b66f-28ea5780caf2)

- [x] Add funds - credit/debit card option
- text below buy with [wallet] button - colour = "text/dark" - possible this colour hasn't been updated on dev side yet. text size = 10px (design on bottom, build on top) 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/0302b0b8-4e07-47d5-943d-40e859dba676)

- [x] Add funds - transfer option
- point 1 has a tooltip, colour should be text-secondary and needs to be lowered to be aligned with text (build on top, design on bottom) 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/6ef1b4c2-f69f-4d22-b7c0-fec441c8d3fb)

### Bugs spotted:
- [x]  If I have account with portis and click _signup_ for new account using email, it logs me in, doesn't allow me to create a new account. Should we have a new step here? "You have previously signed in with Portis using [email], would you like to use this account again?" [will be fixed with #4213]
- Same thing with Torus, i can't choose a different google account, it forces me to previously used account. 
- Fortmatic doesn't have this issue because unique phone number etc, but if i enter a new number will it take me through the onboarding modals again? (it should)

- [x] Seeing known issue we talked about yesterday: the open portis wallet modal appears on sign in. 
 
- [x]  Using brave incognito, portis requires cookies, modal appears, when i close that modal, i'm stuck on the follow instructions modal [tracked here #4181]
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/d39af9f3-7155-4f77-87c0-ea2390e9c275)

**Comment by cillianhunter0** [comment]
- [x] Signup modal - place test bet
- the buttons and 3 dots are not centred
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/67ccd2a1-298a-41b3-8874-21f92ddf60af)

- [x] Dropdowns are opening on top of eachother
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/d823871c-7a46-4405-ad10-5f9bbd2276f6)

Account dropdown - visual issues - highlighted in screenshot (build on left, design on right) 
- [x] can remove the line circled [Track #4250]
- [x] arrow color = text secondary 
- [x] can increase padding between "account" and "address" by 2px
- [x] can tighten up height, see row heights marked to update 
- [x] wallet and gas price labels missing tooltips 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/fc54029c-d531-42d7-92e4-a33db0414191)
