### ISSUE TITLE
Warp Sync

### ISSUE THREAD

**Issue by nuevoalex** [AugurProject/augur#4245]
- [x] Recurring Market
- [x] Generate warp sync data every N (5240?) blocks
- [x] Pin/Publish this data from Augur SDK Server + UI
- [x] How will the UI display this information / how will people report on it?
- [x] SDK server mode that reports on warp sync hash

**Comment by MicahZoltu** [comment]
In order to ensure system security, I believe the Warp Sync Dispute opportunity needs to be automatically checked by clients and presented to users very clearly when available.  One potential option is to have a warning banner if your UI thinks the warp sync report is wrong.  In the banner would be a a link to a dispute page (auto-populated) for it along with information about the situation.  The key is that if a malicious actor reports an incorrect warp sync hash, we need to make sure that within 24 hours _someone_ notices and disputes against them.  If the dispute is hidden away somewhere, it is possible that no one will notice until it is too late and the malicious warp sync hash is already committed.

To incentivize users to look into the matter, we can mention that there is free money if they defend against an attack.

**Comment by joeykrug** [comment]
What's status of this?
