### ISSUE TITLE
[Dev] 0x Trading Support

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#4348]
- [x] Need local mesh node support (in docker)
  - https://0x-org.gitbook.io/mesh/getting-started/deployment
- [x] Once Gnosis Safe used implement wallet signing
   - This will be done with a different signing method, relevant docs:
   - https://github.com/0xProject/0x-protocol-specification/blob/master/v2/v2-specification.md#wallet
   - https://github.com/0xProject/0x-protocol-specification/blob/master/v2/v2-specification.md#signature-types
   - Will *maybe* just be a change from type 0x3 to 0x4 when signing for Wallets.
- [x] Need support for liquidity sorting from 0x orders DB in the market DB
- [x] Once filtering is available implement that and use on testnets
- [x] Once mesh has getOrders functionality make backup behavior where if no connection to client/gateway RPC then browser mesh will be used for the initial syncing
- [x] Once Gateway API is available use that instead of client API
- [x] If initial sync is too slow: Check if order books are stale (if their last pull time was > a couple minutes ago), and then update the order books with this data.
- [x] Add Cancel All -- How do we do this for all orders for this market?

**Comment by pgebheim** [comment]
Current Burn Down list

- 0x cancels batching - Andy
- order ticket doesn't account for if I already have some shares used from open orders - Tom
- Only count for the liquidity sorts/filters up to 3 orders per side of the book per outcome per user per market, filters aren’t working at all atm either. - Tom
- if I update the total order value it doesn't update the quantity to match it anymore
- oh also open orders still say this in the estimation box Max cost of 0.00 $ will be escrowed when making like a new open order that'll go on order book
- fees don't seem to be right in transaction history, also price and quantity are wrong in tx history, and currency says eth. 
- We don’t show tx/gas fees on order estimation (should just add it to estimated fee imo)
- why is the data in the CurrentOrders table wrong? Maybe it's breaking the tx history stuff and filters
- my all time pnl is -$5 but I've gained $45 since making my account, pnl or overall pnl seems to be off somewhere

**Comment by joeykrug** [comment]
awww yeah
