### ISSUE TITLE
uniswap middleware/UI work

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#4358]
#### Middleware integration required for uniswap component.

<img src="https://user-images.githubusercontent.com/1683736/67328602-aedf4000-f4e7-11e9-925c-2380ea4fda43.png" width="333" />

#### TODO
- [x] - Token Swaps (REP <-> DAI) [#7195]
- [x] - ETH/Token Swaps (ETH <-> REP/DAI)
- [x] - Wire up REP rate [#7195]
- [x] - Add Liquidity pooling for tokens (REP/DAI) [#7195]
- [x] - Add Liquidity pooling for eth/tokens (ETH / REP/DAI)
- [x] - UI updates (Processing button) [#7195]

**Comment by robert-e-davidson3** [comment]
Their contracts are currently written in Vyper but they are completing a Solidity version this week. We should hold off on this until then because our contract compilation infrastructure only handles solidity.

**Comment by robert-e-davidson3** [comment]
The API is merged into master. I'll get on integration work when they get their contracts rewritten in solidity, which should be by next week.

**Comment by joeykrug** [comment]
Status of this?

**Comment by joeykrug** [comment]
Update?

**Comment by pgebheim** [comment]
This will be closed along with alex's additions of the uniswap helper contracts (today)

**Comment by pgebheim** [comment]
Actually, after Alex is done it should go back to Andy to be hooked up.

**Comment by Chwy5** [comment]
Working - though confusing flow with eth

Closing this ticket bc this works
