### ISSUE TITLE
Gnosis safe relayer - UI Fees/Gas Work

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#4859]
#### TODO
- [x] Update middleware to support direct gasEstimate calls (via relayer) **[#4955]**
- [x] Use relevant gasEstimate values to display gas estimations in the UI (see below for locations)**[#4955]**
- [x] If relayer returns an error, or falls over, fallback on our current constants as a gas estimate strategy AND convert these values via our uniswap price feed. **[#4955]**
- [x] Transactions fee modal needs to be wired up (Use Gas Relay gasStation). Gas price needs to be set by a present (FAST/AVERAGE/SLOW) or a specific Gas Price amount. [#4891]
- [x] Use gas price set in TX Fee Modal over whatever the relayer suggests for gas price [#4891]
- [x] Copy updates [#4384] **[#4955 ]**

#### UI Locations which display Fees/Gas
      - Create a Market Review (Funds required screen) ✅
      - Trading/Confirm form ✅
      - Withdraw form ✅
      - Gas Fees Modal ✅
      - Disputing Modal ✅
      - Claim Proceeds Modal
      - Get Participation Tokens Modal ✅
      - Migrate V1 to V2 REP Modal ✅
