### ISSUE TITLE
Warp Sync Issues

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#6697]
- [x] offer to report hash to market in UI
- [x] - Fix rollback db issues
- [x] - https://github.com/AugurProject/augur/issues/6310
- [x] Config to disable/enable warp sync generation/pinning (#6758)
- [x] - run https://github.com/cscott/compressjs lzp3 on it (best compression per unit of time spent) to make it even smaller (~~#6810~~) (#6819)
- [x] Add 30 block buffer to checkpoint creation (#6922)
- [x] - 0x order cancels are storing all 0x order cancels, not just augur ones, should fix - Alex
- [x] - store one copy of cancels db
- [x] identify current checkpoint hash via market and UI

Items below have specific tickets:
- [x] - ~~only keep most recent piece of data per primary key per checkpoint~~ Pruning is in PR #6989 
- [x] Flash script for auto-reporting (should run as a long term process that syncs and auto-reports given a key to use)

**Comment by pgebheim** [comment]
Last item here will be done by @robert-e-davidson3

**Comment by pgebheim** [comment]
Closing! Warp sync auto-reporting flash script created.
