### ISSUE TITLE
Trading QA on dev branch

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#8396]
Going through the trading UI on dev branch to fix/address any issues, and bring consistency between v2 and dev.

#### QA:
- [x] trading tutorial [#8366]
- [x] test trading [#8547]
- [x] Add funds Modals (REP/DAI, and all the interactions within the flows)[#8405]
   - [x] fix ProcessingButton [#8605]
   - [x] desktop/mobile flows [#8405]
- [x] Wallet QA
   - [x] Fortmatic
   - [x] torus
   - [x] MM
- [x] Account Summary [#8405]
- [x] Disputing/Reporting
- [ ] Modal QA
  - [ ] Transfer
  - [ ] Migrata REP
  - [x] Disputing/Reporting Guide [#8598]
  - [ ] Withdraw
  - [x] Buy PP [#8565]
  - [x] Disputing
  - [x] Login/Sign
  - [x] Claiming
  - [x] Disclaimer
  - [x] Hardware Wallet [#8547]
  - [x] Account Activation

#### Ghost Inspector Tests:
 - [x] Port v2 test suite over to dev
 - [x] Add GI test for Add Funds flows
