### ISSUE TITLE
Sportsbook Epic Overview Burndown

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#8452]
Sportsbook ToDos:

Markets List
 - [ ] Market cards need to match mocks
 - [ ] responsive updates for tablet/mobile views of market List
 - [x] incorporate updated category sorting and games/futures sorting
 - [ ] update search functionality to handle the search while typing dropdown box
 - [ ] implement detection and clickable switching of combo card sorting of markets.
 - [ ] confirm various states of market (in reporting/finalized) -- make sure outcomes work as expected.

Market Page
 - [x] Outcomes laid out to match mocks -- In progress
 - [ ] responsive updates for tablet/mobile
 - [ ] comment section style update
 - [ ] charts update style
 - [ ] charts update data
 - [x] data for new elements (big squares)
 - [ ] header section to match all mocks and layout

My Bets (portfolio)
 - [ ] responsive updates tablet/mobile
 - [ ] confirm sportsgroup bets "cards" are setup correctly.
 - [ ] make sure search/sorting is accurately working to filter information
 - [ ] looks like layout shifts based on search params. make sure we handle various search states

My Account
 - [ ] responsive updates tablet/mobile
 - [ ] desktop mock adjustments, -- make sure we are matching the mocks
 - [ ] confirm all notifications/alerts are properly being triggered and are styled/formatted correctly.
 - [ ] confirm all new null states are accurate

Betslip
- [ ] responive updates tablet/mobile (mostly complete)
- [x] wire up all actions
- [x] wire up all estimates/data to use real values
- [x] does betslip handle error edge cases?
- [ ] confirm functionality/UX around adding wagers and limits -- so we have upper price limit based on best ask as expected.
- [ ] Where does the `view tutorial` button take the user? <this button appears elsewhere> 
- [x] Should only be able to place a single bet per market and outcome per betslip submission. Cannot make 10 bets around buying outcome A for example.

 OnBoarding:
- [ ] Tutorial / show users how to change odds / use augur etc.
- [ ] Have flow? if not mock out. (we do have flow, find link)
- [ ] TBD Matic onboarding

 ===========================

Data Changes:
 - [x] must hotload sportsgroup markets list -- which requires a shift because we need to grab all markets related to the group, not just market ids.
 - [ ] must hotload a market page (unsure how this can be done due to tech limitations of the blockchain...)
 - [ ] handle sportsgroups in a more global way. Most likely needs to be added to markets context.
 - [x] Review/determine any other hotloading adjustments we may need for various entrypoints into the app.
 - [ ] Review/confirm that we are properly savings/handling all data correctly after converting away from redux. There still may be errors/issues that don't surface easily.
 - [x] finish getter for liquidity

App Misc Changes:
 - [x] allow for links directed to certain themes
 - [x] Odds calculations site wide when changed setting
 - [x] Timestamp changes site wide when changed setting
 - [x] direct link to sportsgroup
 - [x] favorite sportsgroups
 - [ ] performance updates on bottle necked sections of the app. Leverage Context.
 - [ ] make sure all new links to various pages and external resources are setup correctly.

================= *** below can be ignored *** ==================

Nice to Haves:
 - [ ] remove d3 for depth chart and replace with highcharts depth chart
 - [ ] refactor common components to identify repeated patterns. Buttons are a great example.
 - [ ] review/determine if current style of CSS is best going forward
 - [ ] review/determine if our current style of handling data is best going forward
 - [ ] Finally implement a real test suite for the UI that actually tests things tha t matter/non-obvious. Testing various reporting states etc.
 - [ ] Review the folder structure and simplify again in augur-ui.
