### ISSUE TITLE
Next Gen Trading Pg Issues

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#940]
Charts: 

- [x] Candlestick Chart - Volume Bars 

- [x] Candlestick Chart - Top Horizontal Line Showing Eth Cutting Off (only on some markets) (https://github.com/AugurProject/augur/issues/919)

- [x] Candlestick Chart – Add dropdown to see Volume in Eth or Shares

- [x] Candlesticks Chart – gets weird overlapping when changing time Range/Period

- [x]  Candlestick Charts – Limit Range to Past Day, Week, Month All-Time

- [x] Need to adjust volume bar labels depending on candle size. If hourly candles show crosshair time in Day and Hours, if candle is in day just show Time in Days.

- [x] Need allow user to scroll via mouse when Navigator isn't shown b/c of height restriction (400px) only an issue when categorical market has 6+ outcomes.

- [x] Candlestick Charts – Limit Period for past Day to hr, Past wk to hr and Day, Past month to daily, weekly, past yr to daily, weekly, monthly

- [x] Add padding so candlesticks don't cover yAxis price labels

![screen shot 2019-02-17 at 7 08 42 am](https://user-images.githubusercontent.com/3970376/52913354-f6d80400-3282-11e9-8a63-897691c5f3b4.png)

- [x] hide/don't show Volume yAxis. 

- [x] Need better calculation for hover highlight of candle, on large time candles the highlight is beyond the size of the candle.

- [x] Need to add highlight state to volume bar when candlestick is hovered.

- [x] Null state, draw price plotlines

- [x] sparse candles, have chart start at market creation

- [x] Price History Chart _ mouse point not moving on line (https://github.com/AugurProject/augur/issues/918)

- [x] Missing Price History Chart Info Test Cat 3 W vs N 1/25-1/27 (EC)(usually trade on first day of trading is not showing up)

~~- [ ] could we add the vertical lines to the candlestick chart~~ moved to https://app.zenhub.com/workspaces/augur-5bfed3424b5806bc2bf8d173/issues/augurproject/augur/1082

- [x] gap between labels and markets match the design on market depth

- [x] Market Depth Chart – Ask Color needs to change from Pink to Orange (match offer color on Order book)

~~- [ ] All Charts need to be able to zoom In and out, by scrolling of mouse~~
(moved to https://github.com/AugurProject/augur/issues/1071)

- [x] fix edges on depth chart hover tooltip @phoebemirman

Order Ticket: 

- [x] Empty Order ticket – “Place Buy/Sell Order box” colors need to match order book orange and green to start- it is too dull @phoebemirman 

- [x] Order ticket – when entering a sell order to sell quantity 1, then go to limit price and enter .6 (total value fills in) then I enter the 3 (on limit price) b/c I want to sell .63s not .6’s….it changes my quantity to 1.081081081….really all I wanted to do was add an order to sell 1 @0.63 – I think in this scenario it is my total Order Value that needs to change.

- [x] When entering Quantity and Limit price first Total Order Value needs to be adjusted….entering quantity and first decimal spot of limit price works, but when you go to enter second decimal spot of limit price it changes original quantity

- [x] If I click on the order book (filters into order ticket), then clear it and then click the same spot on the order book again nothing happens (nothing enters into the order ticket)

- [x] When user starts with a long position and enters an order to sell out part of it in the order ticket (for example currently long 6 at 0.8, want to sell 1 out at 0.85) Total order Value shows 0 – Should we show the total order value in Eth and under it in (Max cost of Eth to be escrowed show O eth will be escrowed on this order) instead?  - wait to fix this until I get confirmation on how to handle.
In the above example long 6 shares at 0.8 if I plug 0.15 in total order value and price 0.85 I get 7 in quantity – I feel like even if I own shares I should put in total amount like 1 eth and price of .85 and that should give me the quantity …..and then in Max cost of eth escrowed show the amount of .15 being escrowed

- [x] Test Cat 3 W vs N 1/25-1/27 (EC) I am long all 3 outcomes….when I go to add 1 outcome to my current long position I get a warning message about not being profitable and shows a negative profit in the order ticket – probable PnL issue 

- [x] In order ticket – quantity box, if I clear it and hit down or up arrow I get e-8 number in there @phoebemirman 

- [x] When user has open position and enters order which will, close existing position and open a new position in the order ticket, order ticket and charts expand, making charts act weird and look funny @phoebemirman 

- [x] update order form styles and make errors dismissible @phoebemirman 

- [x] update tooltip order form verbiage @phoebemirman (see here https://github.com/AugurProject/augur/issues/826)

- [x] BUG: When user is already long a position, and clicks on an offer on the order book (so user is going to add to their long position)...the message in the order ticket is incorrect...currently shows Closing position, then says Short #of shares @price.....Since user is adding to a long position, it needs to read New Position and Long #shares @price

~~- [ ] If a user has a short position, and goes to cover their short position, adding a buy order to the order ticket, the order ticket only displays "New Position" info and is not displaying the "Closing Position"info~~ moved issue to https://github.com/AugurProject/augur/issues/1225

~~- [ ] (bonus) Quantity input, increment/decrement number by a factor based on cursor location. If input is empty then increment by whole number 1. Example 1.1<cursor>2345 (up arrow) would add 0.1 and (down arrow) would subtract 0.1.~~ moved to <https://github.com/AugurProject/augur/issues/1138>

~~- [ ] Not Profitable error message color is not correct - was changed from blue to a reddish
Please see Matts design~~ removing this pop up. addressed here https://github.com/AugurProject/augur/issues/1140

Misc: 

~~- [ ] Weird issue occurring on desktop when (Windows) when zooming in- starting at 100%. the lower in i make it the charts expand horizontally but the order ticket and order book/trade history shrink up....as the chart increases in size the orderbook/Trade History cant even be seen on the pg anymore.~~

~~- [ ] Might want to set some type of max size limit for users viewing on desktops with large screens....Some tradings will use extra long or extra high screens.~~
addressed in https://github.com/AugurProject/augur/issues/1082

- [x] Current trading pg on snpk still freezes for me after a while

- [x] When I have complete sets to sell, on trading pg in Positions, Line goes too low…should stay even with trade history bottom.

- [x] style top bar tooltip to match mock @phoebemirman
   
- [x] When a user places an order, that order should appear in the Open orders section with a pending box, until that order is filled on the blockchain, then pending box will disappear.  If the order being place results in a full completed trade the trade will be removed from there and show in My fills. We need to wait for 3 confirmations on etherscan before removing. 

- [x] On Open Orders, change 'Escrowed Eth' and 'Escrowed Shares' labels to 'Total Cost (ETH)' and 'Total Cost (Shares)' @phoebemirman 

- [x] Update market header designs @phoebemirman - still needs further updates

- [x] On a market that can be reported on, if I go to the trading pg and hit report button nothing happens @phoebemirman 

- [x] Positions Section on the trading pg is displaying a negative number under quantity (i.e. currently reads Short -2 avg price etc), needs to read Short 2 (NO negative sign) 

- [x] Don't use `...` ellipse to cut off market detail text when in mobile view, wrap the text. so user can read the market description without rotating the phone.

**Comment by Chwy5** [comment]
See ticket 1082 for chart issue burndown

**Comment by bthaile** [comment]
All issues have been addressed or moved to their own tix. closing
