### ISSUE TITLE
Rearchitect getters to use PouchDB

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#963]
The following getters need to be made to work using PouchDB:

- [x] getCategories
- [x] getMarkets
- [x] getMarketPriceCandlesticks
- [x] getMarketPriceHistory
- [x] getTradingHistory
- [ ] getForkMigrationTotals
- [x] getMarketsInfo
- [x] ~~getOrders~~ (not implemented in v2)
- [ ] getReportingSummary
- [ ] getUniversesInfo
- [x] getProceedTradeRows
- [x] getProfitLoss
- [x] getProfitLossSummary
- [ ] getDisputeTokens
- [ ] getInitialReporters
- [ ] getReportingFees
- [ ] getReportingHistory
- [ ] getUserShareBalances
- [x] getUserTradingPositions
- [ ] getWinningBalance
- [ ] getAccountTransferHistory
- [x] getAllOrders
- [ ] getCompleteSets
- [x] ~~getBetterWorseOrders~~ (does not need to be implemented for v2)
- [ ] getDisputeWindow
- [x] ~~getUnclaimedMarketCreatorFees~~ (this shouldn't be needed for v2 since there are no mailboxes)
- [x] getSyncData
- [ ] getDisputeInfo
- [ ] platformActivityStats
- [x] accountTimeRangedStats

**Comment by pgebheim** [comment]
Removed this from the sprint because this is an organizational epic.

**Comment by joeykrug** [comment]
All of these sub issues are done, are the things at the top with checkboxes done or not?

**Comment by adrake33** [comment]
The functions getProfitLossSummary, getAllOrders, getSyncData, & accountTimeRangedStats have been implemented but were not marked as completed. (I've updated them accordingly.) The other unchecked functions have not been implemented.

**Comment by joeykrug** [comment]
I imagine all the reporting ones will be done with the reporting work upcoming soon. What about these non reporting ones, what’s the status on them?:

getUserShareBalances
getWinningBalance
getAccountTransferHistory
getCompleteSets

**Comment by adrake33** [comment]
I think `getUserShareBalances` is not needed since `getUserTradingPositions` returns this info. 

We are planning to deprecate `getAccountTransferHistory` in favor of adding transfers to `getAccountTransactionHistory`:  https://app.zenhub.com/workspaces/augur-5bfed3424b5806bc2bf8d173/issues/augurproject/augur/2489

`getCompleteSets` was not a public getter in v1; however, we have `findCompleteSetsPurchasedLogs` and `findCompleteSetsSoldLogs` in DB.ts, which are used internally by `getAccountTransactionHistory` for retrieving complete sets from PouchDB.

I'm not sure about `getWinningBalance`. @bthaile -- does this need to be implemented? I see there is some code referencing this in the `augur-ui` package that's been commented out.

**Comment by bthaile** [comment]
I have a tix to move “getWinningBalance” from its own getter to users positions. That way we have the information and dont have to have a separate getter.  @adrake33

**Comment by pgebheim** [comment]
This tracking ticket has been broken down into specific epics for getters -- so this particular ticket is now redundant and slightly out of date.

Closing it and relying on the epic-specific tickets.
