### ISSUE TITLE
Create test suite for Augur State

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#964]
Need to talk more with @robert-e-davidson3 on the details for how to create tests for Augur State (a.k.a. Augur Node v2). 

Current tests to create include:

- [x] Syncing (including derived tables if we use them)
- [x] Performing a rollback (including derived tables if we use them)
- [x] Process restarts after crashing in the middle of syncing
- [ ] Process restarts after crashing in the middle of adding new block from blockstream
- [ ] Process restarts after crashing in the middle of a rollback
- [x] Blockstream adds a new block
- [x] Full-text search
- [x] Warp sync
- [x] Getter functions

**Comment by pgebheim** [comment]
@robert-e-davidson3 Tomorrow can you take some time to turn this task into an epic since this will span multiple sprints.

I'd say rough it out into topic area issues that are all sub-8 points and we can schedule them into sprints as need they come up.

It's useful to know that we can make sub-epics and schedule them both within a master epic and a release. should help with these ongoing kinda issues.

**Comment by justinbarry** [comment]
Putting this in backlog as @robert-e-davidson3 is on holiday.

**Comment by robert-e-davidson3** [comment]
Getters are tested.
Blockstream adding a new block: BlockAndLogStreamerListener is tested.

**Comment by pgebheim** [comment]
Closing this big epic, remaining issue is stand-alone with @robert-e-davidson3 deciding if we're doing it and when.
